#
# awinic_sar.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

#
# Source List
#

KO_MODULE_NAME := awinic_sar
KO_MODULE_PATH := $(src)
KO_MODULE_SRC  :=

KO_MODULE_SRC += \
	$(wildcard $(KO_MODULE_PATH)/*.c) \
	$(wildcard $(KO_MODULE_PATH)/comm/*.c) \
	$(wildcard $(KO_MODULE_PATH)/aw963xx/*.c) \
	$(wildcard $(KO_MODULE_PATH)/aw9620x/*.c) \
	$(wildcard $(KO_MODULE_PATH)/aw9610x/*.c)

#
# Build Options
#
ccflags-y += -DDEBUG
ccflags-y += -I$(KO_MODULE_PATH)/comm
ccflags-y += -I$(KO_MODULE_PATH)/aw963xx
ccflags-y += -I$(KO_MODULE_PATH)/aw9620x
ccflags-y += -I$(KO_MODULE_PATH)/aw9610x

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
